// <auto-generated />
using System;
using HomesEngland.Gateway.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HomesEngland.Gateway.Migrations
{
    [DbContext(typeof(AssetRegisterContext))]
    partial class AssetRegisterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HomesEngland.Gateway.AssetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("ActualAgencyEquityCostIncludingHomeBuyAgentFee")
                        .HasColumnName("actualagencyequitycostincludinghomebuyagentfee")
                        .HasColumnType("decimal(13,4)");

                    b.Property<string>("Address")
                        .HasColumnName("address");

                    b.Property<decimal?>("AgencyEquityLoan")
                        .HasColumnName("agencyequityloan")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("AgencyFairValue")
                        .HasColumnName("agencyfairvalue")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("AgencyFairValueDifference")
                        .HasColumnName("agencyfairvaluedifference")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("AgencyPercentage")
                        .HasColumnName("agencypercentage")
                        .HasColumnType("decimal(13,4)");

                    b.Property<string>("ArrearsEffectAppliedOrLimited")
                        .HasColumnName("arrearseffectappliedorlimited");

                    b.Property<int?>("AssetRegisterVersionEntityId");

                    b.Property<int?>("AssetRegisterVersionId")
                        .HasColumnName("assetregisterversionid");

                    b.Property<int?>("CalendarYear")
                        .HasColumnName("calendaryear");

                    b.Property<int?>("Col")
                        .HasColumnName("col");

                    b.Property<DateTime?>("CompletionDateForHpiStart")
                        .HasColumnName("completiondateforhpistart");

                    b.Property<decimal?>("Deposit")
                        .HasColumnName("deposit")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("DeveloperDiscount")
                        .HasColumnName("developerdiscount")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("DeveloperEquityLoan")
                        .HasColumnName("developerequityloan")
                        .HasColumnType("decimal(13,4)");

                    b.Property<string>("DevelopingRslName")
                        .HasColumnName("developingrslname");

                    b.Property<decimal?>("DisposalMonthSinceCompletion")
                        .HasColumnName("disposalmonthsincecompletion")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("DisposalsCost")
                        .HasColumnName("disposalscost")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("DurationInMonths")
                        .HasColumnName("durationinmonths")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("EarlyMortgageIfNeverRepay")
                        .HasColumnName("earlymortgageifneverrepay")
                        .HasColumnType("decimal(13,4)");

                    b.Property<string>("EquityOwner")
                        .HasColumnName("equityowner");

                    b.Property<decimal?>("EstimatedSalePrice")
                        .HasColumnName("estimatedsaleprice")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("EstimatedValuation")
                        .HasColumnName("estimatedvaluation")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("ExpectedStaircasingRate")
                        .HasColumnName("expectedstaircasingrate")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("FairValueReserve")
                        .HasColumnName("fairvaluereserve")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("Fees")
                        .HasColumnName("fees")
                        .HasColumnType("decimal(13,4)");

                    b.Property<bool?>("FirstTimeBuyer")
                        .HasColumnName("firsttimebuyer");

                    b.Property<DateTime?>("FullDisposalDate")
                        .HasColumnName("fulldisposaldate");

                    b.Property<decimal?>("HPIEnd")
                        .HasColumnName("hpiend")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("HPIPlusMinus")
                        .HasColumnName("hpiplusminus")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("HPIStart")
                        .HasColumnName("hpistart")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("HistoricUnallocatedFees")
                        .HasColumnName("historicunallocatedfees")
                        .HasColumnType("decimal(13,4)");

                    b.Property<DateTime?>("HopCompletionDate")
                        .HasColumnName("hopcompletiondate");

                    b.Property<string>("HouseType")
                        .HasColumnName("housetype");

                    b.Property<decimal?>("HouseholdFiftyKIncomeBand")
                        .HasColumnName("householdfiftykincomeband")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("HouseholdFiveKIncomeBand")
                        .HasColumnName("householdfivekincomeband")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("HouseholdIncome")
                        .HasColumnName("householdincome")
                        .HasColumnType("decimal(13,4)");

                    b.Property<DateTime?>("IMSPaymentDate")
                        .HasColumnName("imspaymentdate");

                    b.Property<decimal?>("ImpairmentProvision")
                        .HasColumnName("impairmentprovision")
                        .HasColumnType("decimal(13,4)");

                    b.Property<DateTime?>("ImsActualCompletionDate")
                        .HasColumnName("imsactualcompletiondate");

                    b.Property<DateTime?>("ImsExpectedCompletionDate")
                        .HasColumnName("imsexpectedcompletiondate");

                    b.Property<DateTime?>("ImsLegalCompletionDate")
                        .HasColumnName("imslegalcompletiondate");

                    b.Property<string>("ImsOldRegion")
                        .HasColumnName("imsoldregion");

                    b.Property<int?>("Invested")
                        .HasColumnName("invested");

                    b.Property<bool?>("IsAsset")
                        .HasColumnName("isasset");

                    b.Property<bool?>("IsLondon")
                        .HasColumnName("islondon");

                    b.Property<bool?>("IsPaid")
                        .HasColumnName("ispaid");

                    b.Property<string>("LBHA")
                        .HasColumnName("lbha");

                    b.Property<string>("LocationLaRegionName")
                        .HasColumnName("locationlaregionname");

                    b.Property<string>("MMYYYY")
                        .HasColumnName("mmyyyy");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnName("modifieddatetime");

                    b.Property<int?>("Month")
                        .HasColumnName("month");

                    b.Property<decimal?>("MonthOfCompletionSinceSchemeStart")
                        .HasColumnName("monthofcompletionsinceschemestart")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("Mortgage")
                        .HasColumnName("mortgage")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("MortgageEffect")
                        .HasColumnName("mortgageeffect")
                        .HasColumnType("decimal(13,4)");

                    b.Property<string>("MortgageProvider")
                        .HasColumnName("mortgageprovider");

                    b.Property<decimal?>("NewAgencyPercentage")
                        .HasColumnName("newagencypercentage")
                        .HasColumnType("decimal(13,4)");

                    b.Property<int?>("NoOfBeds")
                        .HasColumnName("noofbeds");

                    b.Property<bool?>("NotLimitedByFirstCharge")
                        .HasColumnName("notlimitedbyfirstcharge");

                    b.Property<decimal?>("OriginalAgencyPercentage")
                        .HasColumnName("originalagencypercentage")
                        .HasColumnType("decimal(13,4)");

                    b.Property<string>("Programme")
                        .HasColumnName("programme");

                    b.Property<string>("PropertyHouseName")
                        .HasColumnName("propertyhousename");

                    b.Property<string>("PropertyPostcode")
                        .HasColumnName("propertypostcode");

                    b.Property<string>("PropertyStreet")
                        .HasColumnName("propertystreet");

                    b.Property<string>("PropertyStreetNumber")
                        .HasColumnName("propertystreetnumber");

                    b.Property<string>("PropertyTown")
                        .HasColumnName("propertytown");

                    b.Property<string>("PropertyType")
                        .HasColumnName("propertytype");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnName("purchaseprice")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("PurchasePriceBand")
                        .HasColumnName("purchasepriceband")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("QuarterSpend")
                        .HasColumnName("quarterspend")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("RegionalSaleAdjust")
                        .HasColumnName("regionalsaleadjust")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("RegionalStairAdjust")
                        .HasColumnName("regionalstairadjust")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("RelativeSalePropertyTypeAndTenureAdjustment")
                        .HasColumnName("relativesalepropertytypeandtenureadjustment")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("RelativeStairPropertyTypeAndTenureAdjustment")
                        .HasColumnName("relativestairpropertytypeandtenureadjustment")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("RemainingAgencyCost")
                        .HasColumnName("remainingagencycost")
                        .HasColumnType("decimal(13,4)");

                    b.Property<int?>("Row")
                        .HasColumnName("row");

                    b.Property<int?>("SchemeId")
                        .HasColumnName("schemeid");

                    b.Property<decimal?>("ShareOfRestrictedEquity")
                        .HasColumnName("shareofrestrictedequity")
                        .HasColumnType("decimal(13,4)");

                    b.Property<decimal?>("StaircasingPercentage")
                        .HasColumnName("staircasingpercentage")
                        .HasColumnType("decimal(13,4)");

                    b.Property<string>("Tenure")
                        .HasColumnName("tenure");

                    b.Property<decimal?>("WAEstimatedPropertyValue")
                        .HasColumnName("waestimatedpropertyvalue")
                        .HasColumnType("decimal(13,4)");

                    b.HasKey("Id");

                    b.HasIndex("AssetRegisterVersionEntityId");

                    b.HasIndex("AssetRegisterVersionId");

                    b.ToTable("assets");
                });

            modelBuilder.Entity("HomesEngland.Gateway.AssetRegisterVersionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnName("modifieddatetime");

                    b.HasKey("Id");

                    b.ToTable("assetregisterversions");
                });

            modelBuilder.Entity("HomesEngland.Gateway.AuthenticationTokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAddress")
                        .HasColumnName("emailaddress");

                    b.Property<DateTime>("Expiry")
                        .HasColumnName("expiry");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnName("modifieddatetime");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnName("referencenumber");

                    b.Property<string>("Token")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.ToTable("authenticationtokens");
                });

            modelBuilder.Entity("HomesEngland.Gateway.AssetEntity", b =>
                {
                    b.HasOne("HomesEngland.Gateway.AssetRegisterVersionEntity")
                        .WithMany("Assets")
                        .HasForeignKey("AssetRegisterVersionEntityId");

                    b.HasOne("HomesEngland.Gateway.AssetRegisterVersionEntity", "AssetRegisterVersion")
                        .WithMany()
                        .HasForeignKey("AssetRegisterVersionId");
                });
#pragma warning restore 612, 618
        }
    }
}
