version: "3.4"
services:
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=super-secret
      - POSTGRES_DB=asset_register_api
    ports:
      - "15432:5432"
  web:
    build: 
      context: .
      target: development
    environment:
      - DATABASE_URL=postgres://postgres:super-secret@localhost:15432/asset_register_api
      - ASPNETCORE_URLS=http://*:5000
    ports:
      - "5000:5000"
    links:
      - db
    volumes:
      - '.:/app'
      # persist the home, as cache goes in it
      - 'home:/root'

volumes:
  home:
