version: "3.4"
services:
  web:
    build: 
      context: .
      target: development
    ports:
      - "5000:80"
    volumes:
      - '.:/app'
      # persist the home, as cache goes in it
      - 'home:/root'

volumes:
  home:
