version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: scripts/build.sh

  test:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: scripts/test.sh

  deploy_staging:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: scripts/deploy.sh staging

  deploy_production:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: echo 'deploy_production' # scripts/deploy.sh production

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy_staging:
          requires:
            - test
      - hold:
          type: approval
          requires:
            - deploy_staging
      - deploy_production:
          requires:
            - hold
