version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    working_directory: asset-register-api
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet publish -c Release -o out

  test:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    working_directory: asset-register-tests
    steps:
      - checkout
      - run: dotnet --info
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
