version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: cd asset-register-api && dotnet restore && dotnet publish -c Release -o out

  test:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: cd asset-register-tests && dotnet test

  deploy_staging:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" | tar -zx
      - run: ./cf api https://api.cloud.service.gov.uk
      - run: ./cf auth "$CF_USER" "$CF_PASSWORD"
      - run: ./cf target -o "$CF_ORG" -s "$CF_SPACE"
      - run: cd asset-register-api && ../cf push

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy_staging:
          requires:
            - test
