version: 2.1

executors:
  dotnet:
    docker:
      - image: microsoft/dotnet:2.1-sdk
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: super-secret
          POSTGRES_DB: asset_register_api 

    working_directory: ~/repo

    environment:
      - DATABASE_URL: postgres://circleci:super-secret@localhost:5432/asset_register_api

jobs:
  build:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet publish -c Release -o out

  test_homes_england:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet test HomesEnglandTest

  test_web_api:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet test WebApiTest

  test_acceptance:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet test AcceptanceTest

  test_gateway:
    executor: dotnet
    steps:
      - checkout
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      - run:
          name: Install Docker client
          command: |
              set -x
              VER="17.03.0-ce"
              curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
              tar -xz -C /tmp -f /tmp/docker-$VER.tgz
              mv /tmp/docker/* /usr/bin
              docker run -d postgres -e POSTGRES_USER=circleci -e POSTGRES_PASSWORD=super-secret -e POSTGRES_DB=asset_register_api
      - run: dotnet test HomesEngland.Gateway.Test

  deploy_dark_staging:
    executor: dotnet
    steps:
      - checkout
      - run: scripts/deploy-dark.sh staging

  flip_staging:
    executor: dotnet
    steps:
      - checkout
      - run: scripts/flip-dark-to-live.sh staging

  revert_staging:
    executor: dotnet
    steps:
      - checkout
      - run: scripts/flip-dark-to-live.sh staging

  deploy_dark_production:
    executor: dotnet
    steps:
      - checkout
      - run: scripts/deploy-dark.sh production

  flip_production:
    executor: dotnet
    steps:
      - checkout
      - run: scripts/flip-dark-to-live.sh production

  revert_production:
    executor: dotnet
    steps:
      - checkout
      - run: scripts/flip-dark-to-live.sh production

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test_homes_england:
          requires:
            - build
      - test_web_api:
          requires:
            - build
      - test_acceptance:
          requires:
            - build
      - test_gateway:
          requires:
            - build
      - deploy_dark_staging:
          requires:
            - test_homes_england
            - test_web_api
            - test_gateway
          filters:
            branches:
              only:
                - master
      - flip_staging:
          requires:
            - deploy_dark_staging
      - hold_revert_staging:
          type: approval
          requires: 
            - flip_staging
      - revert_staging:
          requires: 
            - hold_revert_staging
      - hold_production_deploy:
          type: approval
          requires:
            - flip_staging
      - deploy_dark_production:
          requires:
            - hold_production_deploy
      - hold_flip_production:
          type: approval
          requires:
            - deploy_dark_production
      - flip_production:
          requires:
            - hold_flip_production
      - hold_revert_production:
          type: approval
          requires:
            - flip_production
      - revert_production:
          requires: 
            - hold_revert_production