version: 2.1

executors:
  dotnet:
    docker:
      - image: microsoft/dotnet:2.1-sdk
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: super-secret
          POSTGRES_DB: asset_register_api 

    working_directory: ~/repo

    environment:
      DATABASE_URL: 'postgres://circleci:super-secret@localhost:15432/asset_register_api'

jobs:
  build:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet publish -c Release -o out

  test_homes_england:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet test HomesEnglandTest

  test_web_api:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet test WebApiTest

  test_acceptance:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet test AcceptanceTest

  test_gateway:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet test HomesEngland.Gateway.Test

  deploy_dark_staging:
    executor: dotnet
    steps:
      - checkout
      - run: scripts/deploy-dark.sh staging

  flip_staging:
    executor: dotnet
    steps:
      - checkout
      - run: scripts/flip-dark-to-live.sh staging

  revert_staging:
    executor: dotnet
    steps:
      - checkout
      - run: scripts/flip-dark-to-live.sh staging

  deploy_dark_production:
    executor: dotnet
    steps:
      - checkout
      - run: scripts/deploy-dark.sh production

  flip_production:
    executor: dotnet
    steps:
      - checkout
      - run: scripts/flip-dark-to-live.sh production

  revert_production:
    executor: dotnet
    steps:
      - checkout
      - run: scripts/flip-dark-to-live.sh production

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test_homes_england:
          requires:
            - build
      - test_web_api:
          requires:
            - build
      - test_acceptance:
          requires:
            - build
      - deploy_dark_staging:
          requires:
            - test_homes_england
            - test_web_api
          filters:
            branches:
              only:
                - master
      - flip_staging:
          requires:
            - deploy_dark_staging
      - hold_revert_staging:
          type: approval
          requires: 
            - flip_staging
      - revert_staging:
          requires: 
            - hold_revert_staging
      - hold_production_deploy:
          type: approval
          requires:
            - flip_staging
      - deploy_dark_production:
          requires:
            - hold_production_deploy
      - hold_flip_production:
          type: approval
          requires:
            - deploy_dark_production
      - flip_production:
          requires:
            - hold_flip_production
      - hold_revert_production:
          type: approval
          requires:
            - flip_production
      - revert_production:
          requires: 
            - hold_revert_production