version: 2.1

executors:
  dotnet:
    docker:
      - image: microsoft/dotnet:2.1-sdk

jobs:
  build:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet publish -c Release -o out

  test_homes_england:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet test HomesEnglandTest

  test_web_api:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet test WebApiTest

  test_acceptance:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet test AcceptanceTest

  deploy_staging:
    executor: dotnet
    steps:
      - checkout
      - run: scripts/deploy.sh staging

  deploy_production:
    executor: dotnet
    steps:
      - checkout
      - run: scripts/deploy.sh production

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test_homes_england:
          requires:
            - build
      - test_web_api:
          requires:
            - build
      - test_acceptance:
          requires:
            - build
      - deploy_staging:
          requires:
            - test_homes_england
            - test_web_api
          filters:
            branches:
              only:
                - master
      - hold:
          type: approval
          requires:
            - deploy_staging
      - deploy_production:
          requires:
            - hold
