version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: cd asset-register-api && dotnet restore && dotnet publish -c Release -o out

  test:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: echo pending fix PR4 # cd asset-register-tests && dotnet test

  deploy_staging:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" | tar -zx
      - run: ./cf --version

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy_staging:
          requires:
            - test
