version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: cd asset-register-api && dotnet restore && dotnet publish -c Release -o out

  test:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    working_directory: asset-register-tests
    steps:
      - checkout
      - run: echo pending fix PR4 # cd asset-register-tests && dotnet test
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
